name: transcriptor4ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytest
  - pytest-mock
  - pyinstaller
  - requests
  - setuptools
  - wheel
  - mypy
  - tiktoken
  - ruff
  - pre-commit
  - pip:
      - types-setuptools
      - types-requests
      - customtkinter>=5.2.2
      - tkinterdnd2
      - pillow
      - python-semantic-release>=9.0.0
      - google-genai
      - anthropic>=0.30.0
      - transformers>=4.40.0
      - mistral-common>=1.0.0