name: transcriptor4ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytest
  - pysimplegui
  - pyinstaller
  - requests
  - setuptools
  - wheel
  - mypy
  - tiktoken
  - pip:
      - types-setuptools
      - types-requests